version: '3'

services:
  app:
    container_name: shortener_app
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/usr/src/app/
    working_dir: /usr/src/app/
    networks:
    - shortener-local
    command: python main.py
    ports:
      - 8000:8000
networks:
  shortener-local:
    name: "shorter"
    driver: "bridge"